# riboseq_input <- read.table("riboseq_input.tsv", sep = "\t", header = TRUE)
# usethis::use_data(riboseq_input)
MitoCrypt_longestnte <- read.table("MitoCrypt_longestnte.tsv", sep = '\t', header = TRUE, quote = NULL)
usethis::use_data(MitoCrypt_longestnte)
MitoCrypt_nte_table <- read.table("MitoCrypt_nte_table.tsv", sep = '\t', header = TRUE, quote = NULL)
usethis::use_data(MitoCrypt_nte_table)
MitoCrypt_supported <- read.table("MitoCrypt_supported.tsv", sep = '\t', header = TRUE, quote = NULL)
usethis::use_data(MitoCrypt_supported)
Scer_gtf <- read_gtf_as_data_frame("Saccharomyces_cerevisiae.R64-1-1.91.gtf")
usethis::use_data(Scer_gtf)
